import '../models/dynamic_hypnosis_config.dart';

class DynamicHypnosisSession {
  final String id;
  final String participantId;
  final String? sessionId;
  final String characterChoice;
  final String goal;
  final String voiceId;
  final String voiceName;
  final String scriptText;
  final String? audioStoragePath;
  final int? scriptWordCount;
  final int? audioDurationSeconds;
  final DateTime generationTimestamp;
  final DateTime createdAt;
  final DateTime updatedAt;

  DynamicHypnosisSession({
    required this.id,
    required this.participantId,
    this.sessionId,
    required this.characterChoice,
    required this.goal,
    required this.voiceId,
    required this.voiceName,
    required this.scriptText,
    this.audioStoragePath,
    this.scriptWordCount,
    this.audioDurationSeconds,
    required this.generationTimestamp,
    required this.createdAt,
    required this.updatedAt,
  });

  factory DynamicHypnosisSession.fromJson(Map<String, dynamic> json) {
    return DynamicHypnosisSession(
      id: json['id'] as String,
      participantId: json['participant_id'] as String,
      sessionId: json['session_id'] as String?,
      characterChoice: json['character_choice'] as String,
      goal: json['goal'] as String,
      voiceId: json['voice_id'] as String,
      voiceName: json['voice_name'] as String,
      scriptText: json['script_text'] as String,
      audioStoragePath: json['audio_storage_path'] as String?,
      scriptWordCount: json['script_word_count'] as int?,
      audioDurationSeconds: json['audio_duration_seconds'] as int?,
      generationTimestamp: DateTime.parse(json['generation_timestamp'] as String),
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'participant_id': participantId,
      if (sessionId != null) 'session_id': sessionId,
      'character_choice': characterChoice,
      'goal': goal,
      'voice_id': voiceId,
      'voice_name': voiceName,
      'script_text': scriptText,
      if (audioStoragePath != null) 'audio_storage_path': audioStoragePath,
      if (scriptWordCount != null) 'script_word_count': scriptWordCount,
      if (audioDurationSeconds != null) 'audio_duration_seconds': audioDurationSeconds,
      'generation_timestamp': generationTimestamp.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  /// Create insert payload (without id, created_at, updated_at - server handles these)
  Map<String, dynamic> toInsertJson() {
    return {
      'participant_id': participantId,
      if (sessionId != null) 'session_id': sessionId,
      'character_choice': characterChoice,
      'goal': goal,
      'voice_id': voiceId,
      'voice_name': voiceName,
      'script_text': scriptText,
      if (audioStoragePath != null) 'audio_storage_path': audioStoragePath,
      if (scriptWordCount != null) 'script_word_count': scriptWordCount,
      if (audioDurationSeconds != null) 'audio_duration_seconds': audioDurationSeconds,
      'generation_timestamp': generationTimestamp.toIso8601String(),
    };
  }

  /// Create from DynamicHypnosisConfig and generated content
  factory DynamicHypnosisSession.fromConfig({
    required DynamicHypnosisConfig config,
    required String participantId,
    String? sessionId,
    required String scriptText,
    String? audioStoragePath,
  }) {
    final wordCount = scriptText.split(RegExp(r'\s+')).length;
    final now = DateTime.now();

    return DynamicHypnosisSession(
      id: '', // Will be generated by database
      participantId: participantId,
      sessionId: sessionId,
      characterChoice: config.characterChoice,
      goal: config.goal,
      voiceId: config.voiceId,
      voiceName: config.voiceName,
      scriptText: scriptText,
      audioStoragePath: audioStoragePath,
      scriptWordCount: wordCount,
      audioDurationSeconds: null, // Could calculate from audio file later
      generationTimestamp: now,
      createdAt: now,
      updatedAt: now,
    );
  }
}
