import 'condition.dart';

class Participant {
  final String id;
  final String userId;
  final String? asleepUserId; // User ID generated by Asleep SDK
  final DateTime enrollmentDate;
  final List<Condition> conditionOrder;
  final int currentNight;
  final StudyStatus status;
  final DateTime createdAt;
  final DateTime updatedAt;

  Participant({
    required this.id,
    required this.userId,
    this.asleepUserId,
    required this.enrollmentDate,
    required this.conditionOrder,
    required this.currentNight,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Participant.fromJson(Map<String, dynamic> json) {
    final conditionOrderList = (json['condition_order'] as List<dynamic>)
        .map((e) => Condition.fromString(e.toString()))
        .toList();

    return Participant(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      asleepUserId: json['asleep_user_id'] as String?,
      enrollmentDate: DateTime.parse(json['enrollment_date'] as String),
      conditionOrder: conditionOrderList,
      currentNight: json['current_night'] as int,
      status: StudyStatus.fromString(json['status'] as String),
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      if (asleepUserId != null) 'asleep_user_id': asleepUserId,
      'enrollment_date': enrollmentDate.toIso8601String(),
      'condition_order': conditionOrder.map((c) => c.value).toList(),
      'current_night': currentNight,
      'status': status.value,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  Participant copyWith({
    String? id,
    String? userId,
    DateTime? enrollmentDate,
    List<Condition>? conditionOrder,
    int? currentNight,
    StudyStatus? status,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Participant(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      enrollmentDate: enrollmentDate ?? this.enrollmentDate,
      conditionOrder: conditionOrder ?? this.conditionOrder,
      currentNight: currentNight ?? this.currentNight,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}
